count_new_sub = function(publication_data){
  # This is a helper function for count_new that operates on a publication-specific data frame generated by
  # its parent function
  
  # Gather some metadata about the publication
  metadata = publication_data[1,]
  output = as.data.frame(metadata[c("reference_no","ref_author","ref_pubyr")])
  
  # Count the number of occurences in the publication
  output$n_entries = nrow(publication_data)
  # Count the number of new species described
  output$new_spp = sum(publication_data$is_new_taxon)
  return(output)
}

count_new = function(data, taxon = NULL, resolution = "family", include_non_member = TRUE){
  # Check that taxonomic resolution is valid
  resolution = tolower(resolution)
  levels = c("phylum", "class", "family", "genus", "species_name", "primary_name", "accepted_name")
  if(!(resolution %in% levels)){
    stop(paste("Taxonomic resolution must be one of:", paste(levels, collapse = ", ")))
  }
  
  # Mark which entries are new species
  data$is_new_taxon = !duplicated(data$accepted_no)
  
  # Mark which entriew are new species of the desired family
  if(!is.null(taxon)){
    # If the include_non_fam is true, then retain entries from other families, marked as not new species
    if(include_non_member){
      data$is_new_taxon = data$is_new_taxon & (data[resolution] == taxon)
    }
    # Otherwise, completely remove entries from other families
    else{
      data = data[data[resolution] == taxon,]
    }
  }
  # Reduce the dataset to entries that are either the first instance of a species or the first instance of a publication
  data = data[!duplicated(data$reference_no) | data$is_new_taxon,]
  
  # Split the data by publication
  publist = split(data, data$reference_no)
  # Count the number of new species in each publication
  new_count = lapply(publist, count_new_sub)
  # Combine the resultant data frames
  new_count = do.call(rbind.data.frame, new_count)
  
  # Sort by publication year
  new_count = new_count[order(new_count$ref_pubyr),]
  # Count the cumulative number of species described
  new_count$spp_cumulative = cumsum(new_count$new_spp)
  return(new_count)
}