# Load Packages ----
library(readr)
library(paleobioDB)
library(ggplot2)

# Load data ----

# data = pbdb_occurrences(base_name = c("Lucinidae", "Veneridae", "Mytilidae", "Pectinidae", "Pholadomyidae"), 
#                         max_ma = 250, limit = "all")



load_data = function(){
  data = read_csv("pbdb_data_full.csv", 
                  col_types = cols(accepted_no = col_integer(), 
                                   collection_no = col_integer(), flags = col_character(), 
                                   late_interval = col_character(), 
                                   occurrence_no = col_integer(), ref_pubyr = col_integer(), 
                                   reference_no = col_integer(), reid_no = col_integer(), 
                                   subgenus_name = col_character(), 
                                   subgenus_reso = col_character()), 
                  skip = 21)
  
  # Remove all entries where publication year is missing
  data = data[!is.na(data$ref_pubyr),]
  # Sort data by publication year
  data = data[order(data$ref_pubyr),]
}

data = load_data()

# Data Analysis ----

count_new_sub = function(publication_data){
  # This is a helper function for count_new that operates on a publication-specific data frame generated by
  # its parent function
  
  # Gather some metadata about the publication
  metadata = publication_data[1,]
  output = as.data.frame(metadata[c("reference_no","ref_author","ref_pubyr")])
  
  # Count the number of occurences in the publication
  output$n_entries = nrow(publication_data)
  # Count the number of new species described
  output$new_spp = sum(publication_data$is_new_taxon)
  return(output)
}

count_new = function(data, family = NULL, include_non_fam = TRUE){
  # Mark which entries are new species
  data$is_new_taxon = !duplicated(data$accepted_no)

  # Mark which entriew are new species of the desired family
  if(!is.null(family)){
    # If the include_non_fam is true, then retain entries from other families, marked as not new species
    if(include_non_fam){
      data$is_new_taxon = data$is_new_taxon & (data$family == family)
    }
    # Otherwise, completely remove entries from other families
    else{
      data = data[data$family == family,]
    }
  }
  # Reduce the dataset to entries that are either the first instance of a species or the first instance of a publication
  data = data[!duplicated(data$reference_no) | data$is_new_taxon,]
  
  # Split the data by publication
  publist = split(data, data$reference_no)
  # Count the number of new species in each publication
  new_count = lapply(publist, count_new_sub)
  # Combine the resultant data frames
  new_count = do.call(rbind.data.frame, new_count)
  
  # Sort by publication year
  new_count = new_count[order(new_count$ref_pubyr),]
  # Count the cumulative number of species described
  new_count$spp_cumulative = cumsum(new_count$new_spp)
  return(new_count)
}

year_sub = function(yeardata){
  # This is a helper function for year_sub which analyzes all the publications from a specific year
  output = data.frame(new_spp = sum(yeardata$new_spp))
  output$n_pubs = nrow(yeardata)
  output$ref_pubyr = yeardata[1,]$ref_pubyr
  return(output)
}

year_count = function(pubs){
  # Split the references by year of publication
  year_list = split(pubs, pubs$ref_pubyr)
  # Count the number of references and observed species in each year
  spp_count = lapply(year_list, year_sub)
  output = do.call(rbind, spp_count)
  
  # This part adds the empty rows for years where no relevant papers were published
  year_range = min(pubs$ref_pubyr):max(pubs$ref_pubyr)
  pub_years = pubs$ref_pubyr
  missing_years = year_range[!(year_range %in% pub_years)]
  gapfill = data.frame(ref_pubyr = missing_years, new_spp = 0, n_pubs = 0)
  output = rbind(output, gapfill)
  output = output[order(output$ref_pubyr),]
  
  # Count the cumulative number of species described after each year
  output$spp_cumulative = cumsum(output$new_spp)
  rownames(output) = NULL
  return(output)
}

mytilidae = count_new(data, "Mytilidae")
pectinidae = count_new(data, "Pectinidae")
lucinidae = count_new(data, "Lucinidae")
pholadomyidae = count_new(data, "Pholadomyidae")
veneridae = count_new(data, "Veneridae")

# Plotting ----

plot_pubs = function(pub_data, labels = FALSE, q = 0.99){
  # Plot setup and formatting
  n = 1:nrow(pub_data)
  plt = ggplot(data = pub_data)
  plt = plt + theme_minimal()
  # Plot line
  plt = plt + geom_line(aes(x = n, y = spp_cumulative))
  # Axes and title
  plt = plt + xlab("Number of publications") + ylab("Species described")
  plt = plt + ggtitle("Cumulative number of species described per publication")
  # Add labels for publications that describe many new species
  if(labels){
    is.outlier = pub_data$new_spp > quantile(pub_data$new_spp, q)
    pub_data$name = paste(pub_data$ref_author, pub_data$ref_pubyr)
    pub_data$name[!is.outlier] = ""
    plt = plt + geom_text(aes(x = n, y = pub_data$spp_cumulative-pub_data$new_spp/2, label = pub_data$name),
                          color = "blue")
  }
  return(plt)
}

plot_years = function(pub_data){
  # Plot setup and formatting
  plt = ggplot(data = pub_data)
  plt = plt + theme_minimal()
  # Plot line
  plt = plt + geom_line(aes(x = ref_pubyr, y = spp_cumulative))
  # Axes and title
  plt = plt + xlab("Year") + ylab("Species described")
  plt = plt + ggtitle("Cumulative number of species described per year")
  return(plt)
}
